### ISSUE TITLE
MapBlock: Map not showing in the rendered HTML

### ISSUE THREAD

**Issue by rcdosado** [ibrahimawadhamid/wagtail_blocks#1]
This is the error in Chrome console
> leaflet.js:5 Uncaught Error: Map container not found.
>     at e._initContainer (leaflet.js:5)
>     at e.initialize (leaflet.js:5)
>     at new e (leaflet.js:5)
>     at Object.t.map (leaflet.js:5)
>     at (index):291

I think the cause of the error is in the id attrib which renders empty

`<div id="" style="height: 400px; width: 100%; margin-bottom: 20px;"></div>`

the admin part of the map block is showing a map though. if this isn't an issue can anyone tell me how to correct this?thanks

**Comment by ibrahimawadhamid** [comment]
@rcdosado can you please update to the latest version 0.7.2 and check if the issue still exists.
