### ISSUE TITLE
Some blocks not compatible with Django 3.x

### ISSUE THREAD

**Issue by RubeRuby** [ibrahimawadhamid/wagtail_blocks#4]
Yes I'm aware that officially this is library is not compatible with Django 3. But if this is the only issue it seems it's very little work to do so

Due to the removal of the `{% load staticfiles %}` template tag, blocks that use files like `image_text_overlay` will cause errors.

All instances of the above tag should be replaced with `{% load static %}` . 

Please check [this SO answer](https://stackoverflow.com/questions/55929472/django-templatesyntaxerror-staticfiles-is-not-a-registered-tag-library) for more details.

**Comment by domdinicola** [comment]
@ibrahimawadhamid is this project still maintained?
it looks great, looking forward the opportunity to help you maintaining or forking this

**Comment by ibrahimawadhamid** [comment]
@domdinicola I had plans for this project that I haven't started yet, but I have a lot going on right now. Of course I don't mind the contribution at all.

**Comment by ibrahimawadhamid** [comment]
@RubeRuby I will certainly look into that.

**Comment by ibrahimawadhamid** [comment]
@RubeRuby I've adjusted the compatibility. Please update to the latest version 0.7.2 and check.

**Comment by RubeRuby** [comment]
Sorry I forgot to respond to this. Worked like a charm, thanks! @ibrahimawadhamid
