### ISSUE TITLE
Multiple charts on single page break all charts

### ISSUE THREAD

**Issue by tombola** [ibrahimawadhamid/wagtail_blocks#6]
If I add a single `ChartBlock` to a streamfield works as expected.

If I add multiple `ChartBlock` to the page, none of them are shown.

I am investigating to determine the cause, but if this is known or have tips, would appreciate.

**Comment by ibrahimawadhamid** [comment]
@tombola I haven't looked at the code for a while now, but I would guess it might have to do with the **ID** of the block. Maybe all the blocks are generated with the same ID and that's causing the issue.

**Comment by tombola** [comment]
thanks @ibrahimawadhamid - I have solution, will submit PR.

I think it was instead/aswell that the javascript that populates the chart is added inline in the template and all in the same scope. Adding the same js in a load event closure resolves the issue.
